[tool.bumper]
current_version = "1.1.0"
versioning_type = "semver"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./check_workflow/__init__.py"
search = '__version__ = "{current_version}"'

[[tool.bumper.files]]
file = "./README.md"
search = "@v{current_version}"
