name: Check Template Actions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1 * *"

jobs:
  build-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.x"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Run report
      id: report
      env:
        PUBLIC_PAT: ${{ secrets.PUBLIC_PAT }}
      run: |
        {
          echo 'RES<<EOF'
          uv run --no-dev CheckWorkflow sco1 py-template
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Open Issue If Any Outdated
      if: ${{ steps.report.outputs.RES != ''}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        today=$(date +"%Y-%m-%d")
        gh issue create \
          --title "($today) Outdated Dependency Report" \
          --body '${{ steps.report.outputs.RES }}'
